### ISSUE TITLE
Don't include the binaries

### ISSUE THREAD

**Issue by Eolien55** [biscuitrescue/dwm#1]
You include binaries in this repo (`dwm`) and some useless things such as `config.def.h.orig`

I suggest you to use a .gitignore for this repo and maybe other ones.

**Comment by biscuitrescue** [comment]
uhh i kinda just started using git yesterday extensively so i dont know how do that. ill look it up though and implement it as soon as i can. thank youu

**Comment by Eolien55** [comment]
Oh i thought you used it for more time than that! Git is a very useful tool, you'll see ;)
